apiVersion: v1
kind: Service
metadata:
  namespace: cowrie
  name: honeypot-traefik-ingress

spec:
  ports:
    - protocol: TCP
      name: cowrie
      port: 2222
  selector:
    app: cowrie-honeypot
    
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  namespace: cowrie
  name: honeypot-ssh
  
spec:
  entryPoints:
    - ssh
  routes:
  - match: HostSNI(`*`)
    services:
    - name: honeypot-traefik-ingress
      port: 2222