apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: cowrie
  name: honeypot-log
  
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage