apiVersion: v1
kind: Service
metadata:
  namespace: eco
  name: eco-server

spec:
  type: NodePort
  ports:
    - name: eco
      port: 3000
      protocol: UDP
  selector:
    app: eco-server
 
---
apiVersion: v1
kind: Service
metadata:
  name: eco-server-admin
  namespace: eco

spec:
  ports:
    - name: http
      port: 3001
      protocol: TCP
  selector:
    app: eco-server

---
apiVersion: v1
kind: Service
metadata:
  name: eco-files
  namespace: eco

spec:
  ports:
    - name: sftp
      port: 22
      protocol: TCP
  selector:
    app: eco-server